### ISSUE TITLE
Citations not working as expected

### ISSUE THREAD

**Issue by jraza19** [larahabashy/capstone-report#5]
One piece of feedback from Tom was to have [better in-line citations](https://github.com/UBC-MDS/capstone-gdrl-lipo/blob/master/doc/proposal/report_feedback_gdrl.md). In attempt to fix this, I have attempted the following after reviewing docs for jupyterbook and sphinx-bibtex with no luck:

1) Added `bibtex_reference_style: author_year` to the _config.yaml file
2) Updated sphinx-bibetex library to version 2.2.0
3) Played around with all the available options (cite:p, cite:s..)
4) Copy-paste in their dummy example exactly as it is
5) changed the citation to ``{cite:p} `madden:2021``` as shown in docs [here ](https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#roles-and-directives)

I have found an issue on [jupyterbook github where a trusted MDS faculty/ alumni channel member ](https://github.com/executablebooks/jupyter-book/issues/1346) has posted that he is also not seeing the expected behaviour. Will keep checking this post.

**Comment by TomasBeuzen** [comment]
When things like this come up, I usually go to the [Jupyter Book `_config.yaml` file](https://github.com/executablebooks/jupyter-book/blob/master/docs/_config.yml) and see what they did. That revealed that the correct way to add `bibtex_reference_style: author_year` in `_config.yaml` is:

```yaml
sphinx:
  config:
    bibtex_reference_style: author_year
```

I was then able to change the citation style using directives like `{cite:p}` `{cite:t}` etc. in your report. Let me know if that doesn't work for you!

**Comment by firasm** [comment]
Thanks @jraza19 for flagging this so @TomasBeuzen could find the fix for us :-).

I've [submitted a PR to JupyterBooks](https://github.com/executablebooks/jupyter-book/pull/1367/files) to update the documentation to make this more obvious.

**Comment by jraza19** [comment]
@TomasBeuzen - great tip! Thank you so much, it worked. @firasm - thank you for that submission, I see that it got approved too!!

On a side note - I found it interesting the expected behaviour only works when jupyterbook was installed using pip not conda. Nevertheless, we can close this issue.
